### ISSUE TITLE
Eine Veranstaltung sollte kurzfristig offline geschaltet werden können

### ISSUE THREAD

**Issue by wodo** [dav-kempten/WebTool3#16]
Bei Notfällen ist es notwendig, eine Veranstaltung sehr kurzfristig von der Homepage zu entfernen. Die Geschäftsstellenmitarbeiter müssen in der Lage sein, eine Veranstaltung (auch wenn sie bereits stattgefunden hat) durch einen einfachen Klick auf einen Schalter von der Homepage zu entfernen. Das WebTool muss dann die notwendigen Maßnahmen einleiten, das die Veranstaltung nicht mehr auf der Homepage auftaucht.

**Comment by Bueddi** [comment]
Gute Idee!
