### ISSUE TITLE
Ferienprogramm nur 1 Termin eingetragen

### ISSUE THREAD

**Issue by alinajung** [dav-kempten/WebTool3#9]
Bei den Ferienprogrammen ab Ende Juli und im September ist je nur der erste Programm-Tag eingetragen

**Comment by wodo** [comment]
@alinajung kannst Du mir bitte folgende Daten geben:

- Buchungscodes
- Die fehlenden Termine

Dann können wir das Problem sofort lösen

**Comment by Gabigaebl** [comment]
Hallo Wodo,

anbei die gewünschten Daten:

KFF-906: Mo, 29.07.2019 - 02.08.2019, 08:30 - 16:30
KFC-901: Mo, 29.07.2019 - 02.08.2019, 08:30 - 16:30
KFF-905: Mo, 29.07.2019 - 02.08.2019, 08:30 - 13:30
KFF-909: Mo, 05.08.2019 - 09.08.2019, 08:30 - 16:30
KFF-908: Mo, 02.09.2019 - 06.09.2019, 08:30 - 16:30

Liebe Grüße
Alina



Von: Wolfgang Doll <notifications@github.com>
Gesendet: Freitag, 5. Juli 2019 04:54
An: wodo/WebTool3 <WebTool3@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [wodo/WebTool3] Ferienprogramm nur 1 Termin eingetragen (#9)


@alinajung<https://github.com/alinajung> kannst Du mir bitte folgende Daten geben:

  *   Buchungscodes
  *   Die fehlenden Termine

Dann können wir das Problem sofort lösen

**Comment by wodo** [comment]
@alinajung 
Folgende Punkte Konten korrigiert werden, einige Fragen haben sich neu ergeben:

- KFF-903 29.07.2019 - 02.08.2019, 08:30 - 13:30 (!)
- KFF-905 gibt es nicht, sollte der noch angelegt werden?
- KFF-906 29.07.2019 - 02.08.2019, 08:30 - 16:30
- KFF-908 02.09.2019 - 06.09.2019, 08:30 - 16:30
- KFF-909 gibt's nicht, sollte der noch angelegt werden?
- KFC-901 hat am 17.06.2019 schon stattgefunden, meinst Du KFC-902?
- KFC-902 29.07.2019 - 02.08.2019, 08:30 - 16:30

**Comment by Gabigaebl** [comment]
Hallo Wodo – bei uns sind die Termine so angelegt, wie ich sie dir geschickt habe:


KFF-906: Mo, 29.07.2019 - 02.08.2019, 08:30 - 16:30
KFC-901: Mo, 29.07.2019 - 02.08.2019, 08:30 - 16:30
KFF-905: Mo, 29.07.2019 - 02.08.2019, 08:30 - 13:30
KFF-909: Mo, 05.08.2019 - 09.08.2019, 08:30 - 16:30
KFF-908: Mo, 02.09.2019 - 06.09.2019, 08:30 - 16:30

Ich folgere daraus:

KFF 906 und KFF 908 sind bei uns beiden gleich.
Unser KFF 905 ist bei dir wohl KFF 903
KFF 909 ist das Ferienprogramm Ende August
Und Das Trainingscamp ist das erste in diesem Jahr: also KFC 901

Da ist irgendwie etwas Chaos im System.
Änderst du die Daten bei dir oder wie sollen wir vorgehen?

Liebe Grüße, Alina


Von: Wolfgang Doll <notifications@github.com>
Gesendet: Samstag, 6. Juli 2019 11:37
An: wodo/WebTool3 <WebTool3@noreply.github.com>
Cc: Info DAV-Kempten <Info@dav-kempten.de>; Comment <comment@noreply.github.com>
Betreff: Re: [wodo/WebTool3] Ferienprogramm nur 1 Termin eingetragen (#9)


@alinajung<https://github.com/alinajung>
Folgende Punkte Konten korrigiert werden, einige Fragen haben sich neu ergeben:

  *   KFF-903 29.07.2019 - 02.08.2019, 08:30 - 13:30 (!)
  *   KFF-905 gibt es nicht, sollte der noch angelegt werden?
  *   KFF-906 29.07.2019 - 02.08.2019, 08:30 - 16:30
  *   KFF-908 02.09.2019 - 06.09.2019, 08:30 - 16:30
  *   KFF-909 gibt's nicht, sollte der noch angelegt werden?
  *   KFC-901 hat am 17.06.2019 schon stattgefunden, meinst Du KFC-902?
  *   KFC-902 29.07.2019 - 02.08.2019, 08:30 - 16:30

**Comment by wodo** [comment]
@alinajung 

Ich habe nun folgenden Stand im WebTool:

- [KFC-901](https://www.dav-kempten.de/aktivitaeten/details/KFC-901): 29.07.2019 - 02.08.2019, 08:30 - 16:30
- [KFF-905](https://www.dav-kempten.de/aktivitaeten/details/KFF-905): 29.07.2019 - 02.08.2019, 08:30 - 13:30
- [KFF-906](https://www.dav-kempten.de/aktivitaeten/details/KFF-906): 29.07.2019 - 02.08.2019, 08:30 - 16:30
- [KFF-908](https://www.dav-kempten.de/aktivitaeten/details/KFF-908): 02.09.2019 - 06.09.2019, 08:30 - 16:30
- [KFF-909](https://www.dav-kempten.de/aktivitaeten/details/KFF-909): 05.08.2019 - 09.08.2019, 08:30 - 16:30

Damit hat das Chaos nn hoffentlich eine Ende ;-)
